name: Android Rust Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  android-rust:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Set up Rust
    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        target: aarch64-linux-android

    # Step 3: Set up Android NDK
    - name: Setup Android NDK
      id: ndk
      uses: RaphaelTheriault/setup-android-ndk@v1
      with:
        ndk-version: "23.1.7779620"

    # Step 4: Build and Test
    - name: Build and Test
      env:
        ANDROID_NDK_HOME: ${{ steps.ndk.outputs.android-ndk-path }}
        CC_aarch64_linux_android: ${{ steps.ndk.outputs.android-ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang
        CXX_aarch64_linux_android: ${{ steps.ndk.outputs.android-ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android21-clang++
      run: |
        rustup target add aarch64-linux-android
        cargo build --target aarch64-linux-android
        cargo test --target aarch64-linux-android
